server:  # REST and WS server
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: false
      local: false
    bufferDurationMs: 400  # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000  # How many milliseconds of audio to keep buffered
    trackStuckThresholdMs: 10000   # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    youtubePlaylistLoadLimit: 6  # Number of pages at 100 each
    playerUpdateInterval: 5  # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    # ratelimit:
    #   ipBlocks: ["1.0.0.0/8", "..."]  # list of ip blocks
    #   excludedIps: ["...", "..."]  # ips which should be explicit excluded from usage by lavalink
    #   strategy: "RotateOnBan"  # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
    #   searchTriggersFail: true  # Whether a search 429 should trigger marking the ip as failing
    #   retryLimit: -1  # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    # youtubeConfig:  # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
    #   email: ""  # Email of Google account
    #   password: ""  # Password of Google account
    # httpConfig:  # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
    #   proxyHost: "localhost"  # Hostname of the proxy, (ip or domain)
    #   proxyPort: 3128  # Proxy port, 3128 is the default for squidProxy
    #   proxyUser: ""  # Optional user for basic authentication fields, leave blank if you don't use basic auth
    #   proxyPassword: ""  # Password for basic authentication
  # plugins:
  #   - dependency: "com.github.Topis-Lavalink-Plugins:Topis-Source-Managers-Plugin:v2.0.7" # replace vx.x.x with the latest release tag!
  #     repository: "https://jitpack.io"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 50MB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO

# plugins:
#   topissourcemanagers:
#     providers: # Custom providers for track loading. This is the default
#       - "ytsearch:\"%ISRC%\"" # Will be ignored if track does not have an ISRC. See https://en.wikipedia.org/wiki/International_Standard_Recording_Code
#       - "ytsearch:%QUERY%" # Will be used if track has no ISRC or no track could be found for the ISRC
#     # - "scsearch:%QUERY%" you can add multiple other fallback sources here
#     sources:
#       spotify: true # Enable Spotify source
#       applemusic: true # Enable Apple Music source
#     spotify:
#       clientId: ""
#       clientSecret: ""
#       countryCode: "AU" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
#     applemusic:
#       countryCode: "AU" # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-1
